[project]
name = "phase-edge"
version = "0.1.0"
requires-python = ">=3.10"

[project.scripts]
pe-db-ping = "phaseedge.cli.db:main"
pe-db-info = "phaseedge.cli.db_info:main"

[tool.setuptools.packages.find]
where = ["src"]
